### ISSUE TITLE
It is not easy to collaborate on this project.

### ISSUE THREAD

**Issue by meshy** [sbp/phenny#10]
Hey I was going to do a bit of work based on this project and possibly return some changes to you, but I've had a look at your code, and it seems you are using three space indentation. I was under the impression that python had strict style guidelines about this sort of thing in order to make it easier to share as part of the FOSS philosophy. Frankly, it burns my eyes. Was this indentation intentional, and if so, why?

**Comment by sbp** [comment]
I don't know why I started using 3 spaces, I suppose I picked it up from friends who were doing the same. If I were going to change, I'd probably move to using 2 spaces, because it's less typing and you can pack more in a heavily indented line. I'm sorry that it put you off from contributing!

**Comment by meshy** [comment]
:( If you have that many heavily indented lines, you're doing it wrong. Solving problems caused by breaching one of the python style guides by breaching yet another is just wrong. The standards are there for a reason.
I realise that things like 79 char line length are not always practical, but four space indentation is a must.
