### ISSUE TITLE
Some nicks break commands

### ISSUE THREAD

**Issue by AstraLuma** [sbp/phenny#13]
If the bot's nick contains a pipe, regex commands containing $nick throw errors when being called.

**Comment by sbp** [comment]
This bug was fixed in commit 78ec273 way back on 20 May 2011. Can you try updating your bot code to that or any later commit? If the bug still manifests, can you give an example configuration file that causes the problem?

**Comment by AstraLuma** [comment]
Sorry, this manifested itself in the BotSteve fork. When I filed this, I thought I had checked your code was the same on this.

**Comment by sbp** [comment]
Thanks, no problem!
