### ISSUE TITLE
Everyone can Use Penny

### ISSUE THREAD

**Issue by DrEggman** [sbp/phenny#29]
I am very new to phenny and i very like it. But i noticed that every user can send commands to penny. I first taught the 'admins' are the only people wich can use phenny. Its very difficult if i want to use phenny to moderate IRC-Based chats (like twitch.tv) and users spam around with phenny.

Is there any possibility to make phenny listen only to admins?

Ps: sorry if i did any spelling mistakes :)

**Comment by sfan5** [comment]
Add `if not input.admin: continue` [here](../blob/master/bot.py#L216)

**Comment by DrEggman** [comment]
Thank you, it worked.
