### ISSUE TITLE
Bot does not rejoin after a netsplit

### ISSUE THREAD

**Issue by kihashi** [sbp/phenny#31]
I have the bot on GameSurge, and whenever there is a netsplit that causes the bot's server to get disconnected, the bot never rejoins the channels it was in even though the server rejoined the network. The console still seems to indicate the the bot is connected, but it is not present. I am not sure if this happens on other networks.

**Comment by d3n7** [comment]
How did you fix the issue?

**Comment by kihashi** [comment]
I don't think that I actually resolved this issue. I moved to using [Sopel](
https://sopel.chat/), which is a fork of Phenny. I haven't observed the
problem in long enough that I can't tell you when it last happened.

Cheers
